language: node_js

node_js:
  - 'lts/*'

cache: npm

branches:
  only:
    - master
    - /^greenkeeper/.*$/

script:
  - npm run lint
  - npm run cover
  - npm run build
  - npm link
  - cd ..
  - mkdir site
  - cd site
  - npx yo tsx site 1.2.3 -u surge -n Surge -e surge@github.com --css linaria
    --gc false -b
  - cp build/index.html build/200.html

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - npx codecov -f coverage/lcov.info
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

deploy:
  - provider: script
    script:
      npx semantic-release -r
      https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    skip_cleanup: true
    keep_history: true
    on:
      branch: master
  - provider: surge
    project: ../site/build
    domain: generator-tsx.surge.sh
    skip_cleanup: true
