language: node_js

node_js:
  - 'lts/*'

cache: npm

branches:
  only:
    - master
    - /^greenkeeper/.*$/

script:
  - npm run lint
  - npm run cover

after_success:
  - npx codecov -f coverage/lcov.info
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git remote add pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git -f
  - git checkout master

deploy:
  - provider: script
    script: npm run release -- --yes --git-remote pub
    skip_cleanup: true
    keep_history: true
    on:
      branch: master

notifications:
  email:
    on_success: change
    on_failure: always
