name: Node CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [8, 10, 12]
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install, lint, cover, build, yo
        run: npm install && npm run lint && npm run cover && npm run build && npm link && cd .. && mkdir site && cd site && npx yo tsx site 1.2.3 -u ci -n GitHub -e ci@github.com --css linaria --gc false -b
        env:
          CI: true
      - name: upload coverage report
        if: success()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npx codecov -f coverage/lcov.info || cat coverage/lcov.info
      - name: release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc && npx semantic-release -r https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
