name: Node CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [8, 10, 12]
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: clone
        run: git clone --config core.autocrlf=false https://github.com/generator-tsx.git && cd generator-tsx && git fetch && git checkout $GITHUB_SHA
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install
        run: npm install
        env:
          CI: true
      - name: lint && cover
        if: success()
        run: npm run lint && npm run cover
        env:
          CI: true
      - name: build && link
        if: success()
        run: npm run build && npm link
      - name: yo tsx
        if: success()
        run:
          cd .. && mkdir site && cd site && npx yo tsx site 1.2.3 -u ci -n GitHub -e ci@github.com --css linaria --gc false -b
      - name: upload coverage report
        if: success()
        run: npx codecov -f coverage/lcov.info || cat coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: release
        if: success()
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc && npx semantic-release -r https://${GITHUB_TOKEN}@github.com/generator-tsx.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
