name: Node CI

on: pull_request

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [8, 10, 12]
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: clone
        run: git config --global core.autocrlf false && git clone https://github.com/${GITHUB_REPOSITORY}.git && cd $GITHUB_WORKSPACE && git fetch && git checkout $GITHUB_SHA
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        env:
          CI: true
        run: npm install
      - name: cover
        if: success()
        env:
          CI: true
        run: npm run cover || cat coverage/lcov.info
      - name: build
        if: success()
        run: npm run build
      - name: upload coverage report
        if: success()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npx codecov -f coverage/lcov.info
